<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="holiday-xslt.xsl" type="text/xsl"?>

<!DOCTYPE packages [
<!ELEMENT packages (package*)>
<!--
**** Lachlan Court
**** c3308061
**** SENG1050 Assignment 2
**** 31/10/2020
-->

	<!ELEMENT package (packageName, description, cost, nights, popularity, accommodationOptions+, highlights+, couponCode?, reviews*, images+, externalUrl, contactDetails?)>
		<!ATTLIST package type CDATA #REQUIRED>
		<!ELEMENT packageName (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT cost (#PCDATA)>
		<!ELEMENT nights (#PCDATA)>
		<!ELEMENT popularity (#PCDATA)>
		<!ELEMENT accommodationOptions (location, additionalCost?)>
			<!ELEMENT location (#PCDATA)>
			<!ELEMENT additionalCost (#PCDATA)>
		<!ELEMENT highlights (#PCDATA)>
		<!ELEMENT couponCode (#PCDATA)>
		<!ELEMENT reviews (#PCDATA)>
		<!ELEMENT images (#PCDATA)>
		<!ELEMENT externalUrl (#PCDATA)>
		<!ELEMENT contactDetails (contactName, contactNumber, contactEmail)>
			<!ELEMENT contactName (#PCDATA)>
			<!ELEMENT contactNumber (#PCDATA)>
			<!ELEMENT contactEmail (#PCDATA)>
			
		<!ENTITY p5 "5 stars">
		<!ENTITY p4 "4 stars">
		<!ENTITY p3 "3 stars">
		<!ENTITY p2 "2 stars">
		<!ENTITY p1 "1 stars">
]>

<packages>
	<package type="adventure">
		<packageName>North Sea Crossing</packageName>
		<description>
			This 14 day sailing trip will take you into far into the ocean blue and let you experience what it's like to be a sailor exploring the world for the first time. We'll travel from picturesque Stavanger, Norway across
			the North Sea until we reach the English Coast. From here we'll continue down past the White Cliffs of Dover, have a quick break on the Isle of Wight, before finally making land in Weymouth, England. Along the way you'll
			develop valuable teamwork and leadership skills as you learn how to set and furl sails, navigate, helm, and care for the ship as well as experiencing life on the ocean. You'll truly become part of the crew as you take a
			hand as a watch member and watch the sun rise over the ocean. And of course, what better ways to develop lasting friendships than on a sailing ship. Don't wait, sign up now! Limited spots available.
		</description>
		<cost>800</cost>
		<nights>14</nights>
		<popularity>&p5;</popularity>
		<accommodationOptions>
			<location>2 share dorm</location>
			<additionalCost>0</additionalCost>
		</accommodationOptions>
		<highlights>White Cliffs of Dover</highlights>
		<highlights>Isle of Skye</highlights>
		<highlights>Sailing skills</highlights>
		<couponCode></couponCode>
		<reviews>Love seeing the sunrise over the ocean</reviews>
		<images>images/blueclipper1.jpg</images>
		<images>images/blueclipper2.jpg</images>
		<externalUrl>http://www.maybe-sailing.com/</externalUrl>
		<contactDetails>
			<contactName>Rachel Olsen</contactName>
			<contactNumber>0487562374</contactNumber>
			<contactEmail>rachel.olsen@goholiday.com.au</contactEmail>
		</contactDetails>
	</package>

	<package type="adventure">
		<packageName>Crewman's Capers</packageName>
		<description>
			This sailing adventure is going to conclude with a neat certificate presented to you as a competent crew member! Our experienced trainers will take you out on the water on a five day action packed course to fill you in
			on everything you need to know about how to sail a ship. You will learn about life on board a boat, navigational theory, and safety including the use of flares, liferafts, and man overboard procedures. A competent crew
			RYA qualification is internationally recognised and includes crucial knowledge for those wishing to spend more time at sea.
		</description>
		<cost>2015</cost>
		<nights>5</nights>
		<popularity>&p3;</popularity>
		<accommodationOptions>
			<location>4 share dorm</location>
		</accommodationOptions>
		<highlights>Sailing skills</highlights>
		<couponCode></couponCode>
		<reviews>Very friendly and knowledgable instructors!</reviews>
		<images>images/compcrew.jpg</images>
		<externalUrl>https://pacificsailingschool.com.au/rya-competent-crew/</externalUrl>
		<contactDetails>
			<contactName>Walter Stevenson</contactName>
			<contactNumber>0473856273</contactNumber>
			<contactEmail>walter.stevenson@goholiday.com.au</contactEmail>
		</contactDetails>
	</package>
	
	<package type="adventure">
		<packageName>Day Skipper Escapade</packageName>
		<description>
			This sailing trip will teach you how to be a skipper, how to be the one in charge of a sailing vessel. You'll learn valuable skills such as weather forcasting and ship maintenance, extensive navigational theory and port
			piloting. Experienced trainers will take you on a five day sailing trip anchoring at a different site every evening, giving you plenty of opportunities to fine tune your boat handling skills. The course ends with a
			practical assessment which will grant you an internationally recognised RYA Day Skipper qualification. This is an essential course for those looking to take on more responsibility aboard a sailing vessel.
		</description>
		<cost>5460</cost>
		<nights>5</nights>
		<popularity>&p5;</popularity>
		<accommodationOptions>
			<location>4 share dorm</location>
		</accommodationOptions>
		<highlights>Sailing skills</highlights>
		<couponCode>Love2Sail</couponCode>
		<reviews>Great people and interesting and valuable course!</reviews>
		<reviews>Loved doing this course, so worthwhile!</reviews>
		<images>images/dayskipper.jpg</images>
		<externalUrl>https://pacificsailingschool.com.au/day-skipper/</externalUrl>
		<contactDetails>
			<contactName>Walter Stevenson</contactName>
			<contactNumber>0473856273</contactNumber>
			<contactEmail>walter.stevenson@goholiday.com.au</contactEmail>
		</contactDetails>
	</package>
</packages>