<?xml version="1.0" encoding="utf-8"?><!DOCTYPE packages [
<!ELEMENT packages (package*)>
<!--
**** Lachlan Court
**** c3308061
**** SENG1050 Assignment 1
**** 17/09/2020
-->
	<!ELEMENT package (packageName, description, cost, nights, popularity, accommodationOptions+, highlights+, couponCode?, reviews*, images+, externalUrl, contactDetails?)>
		<!ATTLIST package type CDATA #REQUIRED>
		<!ELEMENT packageName (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT cost (#PCDATA)>
		<!ELEMENT nights (#PCDATA)>
		<!ELEMENT popularity (#PCDATA)>
		<!ELEMENT accommodationOptions (location, additionalCost?)>
			<!ELEMENT location (#PCDATA)>
			<!ELEMENT additionalCost (#PCDATA)>
		<!ELEMENT highlights (#PCDATA)>
		<!ELEMENT couponCode (#PCDATA)>
		<!ELEMENT reviews (#PCDATA)>
		<!ELEMENT images (#PCDATA)>
		<!ELEMENT externalUrl (#PCDATA)>
		<!ELEMENT contactDetails (contactName, contactNumber, contactEmail)>
			<!ELEMENT contactName (#PCDATA)>
			<!ELEMENT contactNumber (#PCDATA)>
			<!ELEMENT contactEmail (#PCDATA)>
			
		<!ENTITY p5 "5 stars">
		<!ENTITY p4 "4 stars">
		<!ENTITY p3 "3 stars">
		<!ENTITY p2 "2 stars">
		<!ENTITY p1 "1 stars">
]>

<packages>
	<package type="Type 1">
		<packageName></packageName>
		<description></description>
		<cost></cost>
		<nights></nights>
		<popularity></popularity>
		<accommodationOptions>
			<location></location>
			<additionalCost></additionalCost>
		</accommodationOptions>
		<highlights></highlights>
		<couponCode></couponCode>
		<reviews></reviews>
		<images></images>
		<externalUrl></externalUrl>
		<contactDetails>
			<contactName></contactName>
			<contactNumber></contactNumber>
			<contactEmail></contactEmail>
		</contactDetails>
	</package>

	<package type="Type 2">
		<packageName></packageName>
		<description></description>
		<cost></cost>
		<nights></nights>
		<popularity></popularity>
		<accommodationOptions>
			<location></location>
			<additionalCost></additionalCost>
		</accommodationOptions>
		<highlights></highlights>
		<couponCode></couponCode>
		<reviews></reviews>
		<images></images>
		<externalUrl></externalUrl>
		<contactDetails>
			<contactName></contactName>
			<contactNumber></contactNumber>
			<contactEmail></contactEmail>
		</contactDetails>
	</package>
	
	<package type="Type 3">
		<packageName></packageName>
		<description></description>
		<cost></cost>
		<nights></nights>
		<popularity></popularity>
		<accommodationOptions>
			<location></location>
			<additionalCost></additionalCost>
		</accommodationOptions>
		<highlights></highlights>
		<couponCode></couponCode>
		<reviews></reviews>
		<images></images>
		<externalUrl></externalUrl>
		<contactDetails>
			<contactName></contactName>
			<contactNumber></contactNumber>
			<contactEmail></contactEmail>
		</contactDetails>
	</package>
</packages>